### ISSUE TITLE
export_to_vtk fails with Dolfin 2017.1.0

### ISSUE THREAD

**Issue by ahellander** [ahellander/pyurdme#163]
Traceback (most recent call last):
  File "simple_diffusion.py", line 37, in <module>
    result.export_to_vtk("A", "output")
  File "/home/ubuntu/pyurdme/pyurdme/pyurdme.py", line 1753, in export_to_vtk
    fd = dolfin.File(os.path.join(folder_name, "trajectory.xdmf").encode('ascii', 'ignore'))
  File "/usr/lib/python2.7/dist-packages/dolfin/cpp/io.py", line 551, in __init__
    _io.File_swiginit(self, _io.new_File(*args))
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to open file.
*** Reason:  Unknown file type (".xdmf") for file "output/trajectory.xdmf".
*** Where:   This error was encountered inside File.cpp.
*** Process: 0
*** 
*** DOLFIN version: 2017.1.0
*** Git changeset:  unknown
*** -------------------------------------------------------------------------

**Comment by ahellander** [comment]
This is due to a docuemented change in the Dolfin interface, from ChangeLog:

****
Remove XDMF from File interface. XDMF is XML based, and has many possibilities for file access, which are not accessible through the limited File interface and “<<” “>>” operators. Instead of File, use XDMFFile, and use XDMFFile.read() and XDMFFile.write() for I/O. Demos and tests have been updated to show usage. XDMF now also supports ASCII I/O in serial, useful for compatibility with users who do not have the HDF5 library available.
